
<div id="header">

 <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
  <div class="inner">

  <p id="skip" class="hide"><a href="#content">Skip to Content</a></p>


  <h2 class="hide">Menu CargarInCloud</h2>
  <div id="nav">
  <ul id="main-menu" class="sm sm-blue"><li id="menu-item-20"><a title="Go to home page" href="../home/Admin/index.php"><span id="logo-menu">Condor v.1.0</span> </a></li>
<li id="menu-item-8"><a href="#">Configuracion</a>
<ul class="sub-menu">
    <li id="menu-item-24"><a href="../actividad/index.php">Actividades</a></li>
    <li id="menu-item-152"><a href="../causpen/index.php">Causa Pendiente</a></li>
    <li id="menu-item-193"><a href="../ciudad/index.php">Ciudades</a>
    <li id="menu-item-193"><a href="../empleado/index.php">Empleados</a>
    <li id="menu-item-193"><a href="../formapago/index.php">Formas de Pagos</a>
    <li id="menu-item-193"><a href="../intervencion/index.php">Intervenciones</a>
    <li id="menu-item-193"><a href="../perfil/index.php">Perfiles de Usuarios</a>
    <li id="menu-item-193"><a href="../plazopago/index.php">Plazos</a>
   <li id="menu-item-193"><a href="../equipo/index.php">Equipos</a>

  <ul class="sub-menu">
          <li id="menu-item-152"><a href="../capacidad/index.php">Capacidad</a></li>
          <li id="menu-item-193"><a href="../combustible/index.php">Combustible</a>
          <li id="menu-item-193"><a href="../etapa/index.php">Etapas</a>
          <li id="menu-item-193"><a href="../frecuencia/index.php">Frecuencias</a>
          <li id="menu-item-193"><a href="../tipomotor/index.php">Motores</a>
  </ul>
</li>
  </ul>
</li>

<li id="menu-item-8"><a href="#">Registros</a>
<ul class="sub-menu">
    <li id="menu-item-24"><a href="../empleado/index.php">Empleado</a></li>
    <li id="menu-item-152"><a href="../usuario/index.php">Usuarios</a></li>
    <li id="menu-item-193"><a href="../equipo/index.php">Equipos</a>
    <li id="menu-item-193"><a href="#">Mantenimientos</a>

  <ul class="sub-menu">
          <li id="menu-item-152"><a href="../mantecorrect/index.php">Correctivo</a></li>
          <li id="menu-item-193"><a href="../manteprevent/index.php">Preventivo</a>
      
  </ul>
</li>
  </ul>
</li>

<li id="menu-item-8"><a href="../home/Admin/reportes.php">Reportes</a>
<li id="menu-item-989"><a title="usuario" </span> <span class="UserLogin"></span>Bienvenido  <?php echo "<b>".$_SESSION['razon']."</b>"; ?></a>
<ul class="sub-menu">
    <li id="menu-item-198"><a href="../includes/logout.php"><span data-rel="external">Salir</span></a></li>
    </ul>
</li>



</ul>  </div>
  <!-- #nav end -->

  </div>
 </div>










