
<div id="header">

 <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
  <div class="inner">

  <p id="skip" class="hide"><a href="#content">Skip to Content</a></p>


  <h2 class="hide">Menu CargarInCloud</h2>
  <div id="nav">
  <ul id="main-menu" class="sm sm-blue"><li id="menu-item-20"><a title="Go to home page" href="/Cliente/index.php"><span id="logo-menu">Condor v.1.0</span> </a></li>


<li id="menu-item-8"><a href="../reportes.php">Reportes</a>
<li id="menu-item-8"><a href="../equipo/index.php">Equipos</a>


</li>
<li id="menu-item-989"><a title="usuario" </span> <span class="UserLogin"></span>Bienvenido  <?php echo "<b>".$_SESSION['razon']."</b>"; ?></a>
<ul class="sub-menu">
    <li id="menu-item-198"><a href="../logout.php"><span data-rel="external">Salir</span></a></li>
    </ul>
</li>



</ul>  </div>
  <!-- #nav end -->

  </div>
 </div>






